### ISSUE TITLE
Fail displaying colors after saving

### ISSUE THREAD

**Issue by bryanmaina** [chrisbra/Colorizer#49] opened 2016-11-15 13:39 UTC
The plugin... 

1. works when I open a file
2. then fails when I save the file
3. but it works on the line where the cursor works

While opening some files it just don't work until you save the file and will then work only on the line with the cursor.

**After opening**
![vim-css-after-open](https://cloud.githubusercontent.com/assets/8012851/20307496/04402a04-ab40-11e6-8195-7876e448000e.png)

**After saving with no cursor on a line with color declaration**
![vim-css-after-save-not-line](https://cloud.githubusercontent.com/assets/8012851/20307503/0d4b9d5e-ab40-11e6-9af4-5915f989c56d.png)

**After saving with a cursor on a line with color declaration**
![vim-css-after-save-on-line](https://cloud.githubusercontent.com/assets/8012851/20307506/12358172-ab40-11e6-8e88-03cab50b2c0e.png)

**Comment by chrisbra** [comment] 2016-11-16 17:18
cannot reproduce.

**Comment by chrisbra** [comment] 2018-08-08 06:44
closing as unreproducible

**Closed by chrisbra** 2018-08-08 06:44 UTC
