### ISSUE TITLE
is there a working possiblity to have this feature working automatically?

### ISSUE THREAD

**Issue by joe23rep** [chrisbra/Colorizer#79] opened 2020-01-11 00:56 UTC
like the title says id like to have this feature on without typing :ColorHighlight everytime i want to use it.

i know i could come up with a shortcut for it but i like it so id like to have it autostarted. 

everything i tried so far didnt work out

**Comment by chrisbra** [comment] 2020-01-11 13:08
Have you read the help?

**Comment by chrisbra** [comment] 2020-01-13 10:38
possible duplicate of #78

**Comment by Goku-San** [comment] 2020-02-29 11:21
Hello @chrisbra @joe23rep , I run in to this problem a while ago, and I manage to solve it by putting this in my **.vimrc** ```autocmd BufEnter,BufLeave *.css,*.scss,*.sass :ColorHighlight!``` and it works like a charm, no *flickering* and only for those file extensions.

I deducted this from @daveyarwood 's answer on [77](https://github.com/chrisbra/Colorizer/issues/77#issuecomment-554065859)

Hope this helps as a future reference.

**Comment by daveyarwood** [comment] 2020-02-29 16:20
I think we can probably close this as a duplicate of #77, as I'm trying to work toward the same objective. :)

**Comment by scrouthtv** [comment] 2020-05-05 11:18
In case anyone is wondering the correct way is using
```
let g:colorizer_auto_color = 1
```
not an `autocmd`. If you open large files, the `autocmd` method takes forever to startup, while `g:colorizer_auto_color` is nearly instant:
```
 $ wc -l test.log
11052
// this time with let g:colorizer_auto_color = 1:
$ time nvim test.log -c :q
nvim test.log -c :q  0.13s user 0.05s system 96% cpu 0.280 total
// this time with autocmd:
$ time nvim test.log -c :q
nvim test.log -c :q  5.27s user 0.05s system 96% cpu 0.280 total
```

I am running this test on a fairly decent pc. 

In the above example, I guess it would make even more sense to use `g:colorizer_auto_filetype` because log files aren't likely to have color codes (?).

**Comment by scrouthtv** [comment] 2020-05-05 11:18
Also see https://github.com/chrisbra/Colorizer/blob/61b652b3c97fb42f06557f62f783ca810975dc8a/doc/Colorizer.txt#L128 and https://github.com/chrisbra/Colorizer/blob/61b652b3c97fb42f06557f62f783ca810975dc8a/doc/Colorizer.txt#L140

**Comment by kajzersoze** [comment] 2020-05-09 12:34
In my case this works `let g:colorizer_auto_color = 1` but you have to move the vim cursor and the colors will appear after 3 seconds.

**Closed** 2020-05-29 19:32 UTC
