### ISSUE TITLE
Error when running ColorToggle with rgba colors present

### ISSUE THREAD

**Issue by gandalf3** [chrisbra/Colorizer#61] opened 2018-08-07 21:10 UTC
When running ColorToggle with a file with any rgba colors, e.g:

```rgba(0, 0, 0, 1)```

I get the following error:

```
Colorizer: Some error occured here:  Colorize: ['rgba(\s*\%(\d\+%\?\D*\)\{3}\%(\%(0\?\%(.\d\+\)\?\)\|1\))', function('<SNR>102_ColorRGBValues'), 'colorizer_rgba', 1, []]
Colorizer: Position: [0, 1, 1, 0]
```

Running in NVIM v0.3.1

**Comment by chrisbra** [comment] 2018-08-08 06:09
Please test in Vim. I cannot reproduce the problem here with Vim 8.1.193.

**Comment by gandalf3** [comment] 2018-08-09 23:25
Sure enough it works in vim here as well. Is neovim not supported?

**Comment by chrisbra** [comment] 2018-08-10 06:19
Well, I am not using neovim, but I don't remember using any Vim specifics (it's not the job api) here. Since neovim claims to be compatible with Vim, this should be raised with their devs. I cannot guess what problem neovim has here.

**Comment by chrisbra** [comment] 2018-08-22 09:27
closing, as this does not seem to be a bug in this plugin.

**Closed by chrisbra** 2018-08-22 09:27 UTC
