### ISSUE TITLE
Invisible dark colors on dark terminal in swapped_bg_fg mode

### ISSUE THREAD

**Issue by msva** [chrisbra/Colorizer#51] opened 2017-02-11 11:21 UTC
As far as I looked in code, it is impossible to set some "magic" variable to say that I using dark terminal, so dark colors in swapped mode should be a bit lighter (to be able to see them).
It results in following behaviour:
![screenshot_20170211_181448](https://cloud.githubusercontent.com/assets/268102/22853322/016b3b1c-f086-11e6-8a84-8f9f74fce821.png)
As you can noticed, it is also effect of issue #50, that named colors, and manually aliased colors does not apply.
But even if I use "workaround" I mentioned in #50 (opening multiple files), and have `#000000` aliased to `#444444` it is anyway `#` still rendered with invisible black color:
![screenshot_20170211_035523](https://cloud.githubusercontent.com/assets/268102/22853229/3dc42e0a-f083-11e6-9cdd-0eed06549ba9.png)

**Comment by msva** [comment] 2017-02-11 11:26
So, I'd very like to somehow tell 'all colours of grey palette that darker than `#262626` should be rendered as `#262626`', but I can't see the way to do that, except manually alias all of that 25 colors in `g:colorizer_custom_colors` (but bug #50 prevents it anyway) or patching the code :(

**Comment by chrisbra** [comment] 2017-02-11 12:11
It's supposed to colorize the colors according to their values. It doesn't make sense to color them differently. Also, I don't understand what you mean with "bug #50 prevents it anyway".

**Comment by msva** [comment] 2017-02-11 12:43
> It's supposed to colorize the colors according to their values.
> It doesn't make sense to color them differently.

Yes, I understand, that it is supposed to "colorize according to their vaues". 
but:

1) in 256-color terminal most of colors is anyway colored not in their value, 
but in "similar" value (but it is okay, since user (me, at least) just wants 
to know the kind of the color, but not the exact value. Especially, since it 
is impossible to render 65536 colors in 256-colored terminal)

2) Dark foreground on dark background is invisible. Just as dark background of 
the text is invisible on dark terminal background.

So user (me, at least) does not see that text at all. And I'm (and, maybe, 
other people are) okay with sacrificing exact colour matching of few colors for 
ability to see them. So, that's why I think that some offset (to make darker 
colors a bit lighter) is needed.

3) Anyway, I'd be pretty fine with manual aliasing, if `#` will be colored in 
aliased color too (and if #50 will be fixed) :)

> Also, I don't understand what you mean with "bug #50 prevents it anyway".

I meant, that I wouldn't maybe even report this issue and used colors 
aliasing, if I didn't experience issue #50 (it affects not only most named 
colors, but also `custom` ones).

**Comment by chrisbra** [comment] 2017-02-11 14:00
So that only happens when using `:ColorSwapFgBg`?

**Comment by msva** [comment] 2017-02-11 15:17
> So that only happens when using `:ColorSwapFgBg`?

Depends on what do you mean by "that" :)

If you meant rendering of `#` in another color than hex-code, then yes.

If you meant "issue #50", then no. It happens in any case.

If you meant invisibility of the color, then answer is not so simple... It is happens in any case:
- with swapping enabled, it is text almost-invisible,
- with swapping disabled, text, at least, is visible, but it is background almost-invisible (I see only white bold text on almost black background), and it is anyway hard to visually differentiate `#000000` from `#202020` and `#222222`.
![screenshot_20170211_220224](https://cloud.githubusercontent.com/assets/268102/22854692/e7d65e90-f0a6-11e6-9426-23976e34b451.png)

So, if it is anyway hard to differentiate them, why just not have a way to add an offset? 😎 It anyway will be impossible to visually differentiate them, but at least it will be visible text in swapped mode (which I like more than default mode, since it not hurt eyes at night ;)

**Comment by chrisbra** [comment] 2017-02-11 16:58
Hi Vadim!

On Sa, 11 Feb 2017, Vadim A. Misbakh-Soloviov wrote:

> > So that only happens when using `:ColorSwapFgBg`?
> 
> Depends on what do you mean by "that" :)
> 
> If you meant rendering of `#` in another color than hex-code, then yes.
> 
> If you meant "issue #50", then no. It happens in any case.
> 
> If you meant invisibility of the color, then answer is not so simple... It is happens in any case:
> - with swapping enabled, it is text almost-invisible,
> - with swapping disabled, text, at least, is visible, but it is background almost-invisible (I see only white bold text on almost black background), and it is anyway hard to visually differentiate `#000000` from `#202020` and `#222222`.
> ![screenshot_20170211_220224](https://cloud.githubusercontent.com/assets/268102/22854692/e7d65e90-f0a6-11e6-9426-23976e34b451.png)
> 
> So, if it is anyway hard to differentiate them, why just not have a way to add an offset? 😎 It anyway will be impossible to visually differentiate them, but at least it will be visible text in swapped mode (which I like more than default mode, since it not hurt eyes at night ;)

I can certainly do that and add an offset. However I wonder how you want 
this to be defined. Add an offset, if R*G*B is smaller than a predefined 
value?

Best,
Christian
-- 
Atheisten:
  Leute, die einen Glauben, den sie nicht haben, glühend verteidigen.

**Comment by msva** [comment] 2017-02-11 19:09
> I can certainly do that and add an offset. However I wonder how you want
> this to be defined. Add an offset, if R*G*B is smaller than a predefined
> value?

1) Yeah, now, with fix of #50, I see some "offsetting" (making color gray), but with strange conditions:

a) has sign is not colored in offsetted color, but in original (so, invisible if color is black).

b) in case of "synchronized" values of "channels" (i.e. something like: `R == G == B == DecToHex(X)`): it is gray, while `X` is in range of `00` to`04` (i.e. `#000000`, ... ,`#040404`). Starting from `X=05` (which is still invisible) it is not offsetted anymore and renders black. But it becomes visible only somewhere around `X=19`, or better `X=23`:

![screenshot_20170212_012006](https://cloud.githubusercontent.com/assets/268102/22856634/98e2d63a-f0c7-11e6-845f-e37e1c4004ad.png)

c) if it is not synchronized, then it is gray until value of some channel reaches `0x30` (and has-sign is black). Since any of channel reaches 0x30 — all the string displayed in the color of that channel (or, if it is two channels with value of `>=0x30`, it renders in color of that channels mixed althogether (looks like in case of unsynchronized channels it assuming that if channel's value is less than 0x30, then it is 0). In some cases this assumption fails:

![screenshot_20170212_020054](https://cloud.githubusercontent.com/assets/268102/22856639/bfff507c-f0c7-11e6-9ba7-ef43f8309ce8.png)


And even if I had some ideas about per-channel offset before testing `c)`, for now I can't describe a fail-less offset algorithm :)

**Comment by msva** [comment] 2017-02-11 19:19
I guess (not tested), that assuming that value of any channel is equal to 0x19 while it less than 19 can fix both `b)` and `c)` issues. But it requires testing :)

And, `a)` requires separate fix :)

If any, I tested with
```zsh
$ echo 'h1 {' > /tmp/moo.css; for r in `seq 0 5 50`; do for g in `seq 0 5 50`; do for b in `seq 0 5 50`; do print -f 'color: #%02x%02x%02x;\n' $r $g $b >> /tmp/moo.css; done;done;done; echo '}' >> /tmp/moo.css; vim /tmp/moo.css
```
(file is about 21Kb, and about 1.5KLOC)

**Comment by chrisbra** [comment] 2017-02-11 19:25
Thanks that is helpful. I leave that open for now. I am not quite sure if that is all correct. Can you please check in a gvim window with `:colorscheme default` (e.g. a white backgroud)?

**Comment by msva** [comment] 2017-02-12 11:57
I tested in gvim with light theme. Although, it is a bit hard for me to differentiate colors on white background, it seems, there it don't fail on that lower colors (so it is only affect terminal vim):
![screenshot_20170212_184304](https://cloud.githubusercontent.com/assets/268102/22861834/085f8f7a-f155-11e6-9402-eb3ddb35d86e.png)

**Comment by msva** [comment] 2017-02-13 16:21
ping? ;)

**Comment by chrisbra** [comment] 2017-02-13 18:44
"patience you need" I am doing it here in my spare time. I cannot promise you anything here. Additionally since it looks okay with a light background, I suspect either a terminal configuration issue on your side or even a vim bug, but nothing that my plugin could cure.

**Comment by msva** [comment] 2017-02-13 19:16
> "patience you need" I am doing it here in my spare time. I cannot promise
> you anything here.

I just pinged in caes if notification can be missed (I personally sometimes 
miss reply notifications in all of mt email flow, even with IMAP sorting) :-)
Don't take it as any kind of complain, please :-)

> Additionally since it looks okay with a light background, I suspect either a 
terminal configuration issue on your side or even a vim bug, but nothing that 
my plugin could cure.

Actually, it is not the whole truth. It works fine even with dark bg even with 
also swap_bgfg=1. But in gvim, not terminal vim.
While both terminal vims (NeoVim and "old shiny" vim-8.0) shows `<0x30` colors 
as gray.

And yes, it surely can be a (both) vims bug, but I'll try to play with plugin 
code, to be sure, if you don't mind (so, don't close the issue for now, 
please).

**Comment by chrisbra** [comment] 2017-06-27 15:18
sorry, for not coming back. Is there anything missing. I kind of lost track what the status is currently

**Comment by chrisbra** [comment] 2017-06-27 15:20
If you comment out [this](https://github.com/chrisbra/Colorizer/blob/master/autoload/Colorizer.vim#L1475) and set those variables, is that what you want? ( i just noticed I committed that by accident, since I haven't worked with that repo for quite some while, but if that is useful, I will go ahead and fix that and add some documentation. What do you think?

**Comment by msva** [comment] 2018-03-25 06:42
Well, Now it is me who sorry for the long delay. And it seems, that there was some more commits that touched that file since your message, so it is quite inobvious what exactly variables did you mean.
And at the time of eb26e1d7fdabc92e09bb7e56b7cc75d2a6019489 (right before your message) it seems that line pointed to `return a:list` (which, by the way, still there). Is that dhat you meant?

// by the way, doesn't `return smth` on first line inside function stopping the function execution?

**Comment by msva** [comment] 2018-03-25 06:52
Well, anyway, the second problem (missed coloring) can only be reproduced with termguicolors disabled (i.e. when it enabled, all the coloring works fine), so it mostly looks like a RgbHex->term translator bug.

And returning back to first issue (black fg on black bg) it would be nice if it would be possible to not only add "custom" named colors, but alias one hex color to another (say `#000000 -> #212121`), or, maybe, a possibility to explicitly define colors which shouldn't obey "SwapBgFg" (and anyway keep color as bg).

**Comment by chrisbra** [comment] 2018-03-25 12:09
sorry I am totally lost. Let me close this for now. Please open a new request with exact steps to reproduce. I'll have a look then. Sorry for the inconvenience.

**Closed by chrisbra** 2018-03-25 12:09 UTC
