### ISSUE TITLE
Colorizer not operational

### ISSUE THREAD

**Issue by bearcatsandor** [chrisbra/Colorizer#56] opened 2017-08-15 05:05 UTC
I'm not sure if i'm doing something wrong here, but as you can see by the screenshot attached, i'm not getting css colors. 

![2017-08-14_23 00 48](https://user-images.githubusercontent.com/57407/29302801-80c41268-8144-11e7-8a98-e07299121305.png)
Would you mind taking a look in case someone else may be having a similar issue or there is a conflict with another plugin that needs to be reported?

My config is pasted at https://gist.github.com/bearcatsandor/79d8fe5c0bd51bc506d2e06203e792d3

Colorizer *is* loaded according to :scriptnames 

Thank you

**Comment by chrisbra** [comment] 2017-08-15 05:40
it does not work automatically all by itself. Please read the help.

duplicate of #54

**Closed by chrisbra** 2017-08-15 05:40 UTC

**Comment by bearcatsandor** [comment] 2017-08-15 17:36
Almost every plugin that i've encountered doesn't need anything more than to load it, to make it do something.

Since you've had two bugs on this (and will probably get more), i suggest putting something along the lines of the following under 
Usage in the readme.md:

> To activate for all file types (not recommended), place :let g:colorizer_auto_color = 1 into your vimrc.
> 
> To activate for selected file types (ex. html and css), place :let g:colorizer_auto_filetype='css,html' into your vimrc.
>

**Comment by chrisbra** [comment] 2017-08-15 20:49
On Di, 15 Aug 2017, Bearcat M. Şándor wrote:

> Almost every plugin that i've encountered doesn't need anything more
> than to load it, to make it do something.

Yes, and that is what it does. It is readily available and provides a 
couple of commands. The reason it does not color automatically, is, that 
I wanted it to be readily available for any filetype, no matter what. 
But at the same time, do not want impact performance to much, when it is 
not needed. Therefore, I created a version, that will do what you want. 
You just have to tell it to do it.

And I actually prefer it that way, than having to think about all 
different autocommands needed to have it work magically for - well which 
filetype exactly? Type `:Color` and press <C-D> and you can see all 
commands available with this plugin. I consider this a feature.

> Since you've had two bugs on this (and will probably get more), i

You mean, nobody is reading the help anymore? There is a reason I 
provide documentation with my plugin. It should always be the first look 
after installing a plugin to understand how it works and what it 
actually does. That is also what the readme says:

> Once installed, take a look at the Colorizer help at :h Colorizer

And yes, it is a strange coincident, that this is the second bugreport 
about not reading the documentation within a couple of days, while all 
the years before, every user did not encounter it.  

> suggest putting something along the lines of the following under 
> Usage in the readme.md:
> 
> > To activate for all file types (not recommended), place :let g:colorizer_auto_color = 1 into your vimrc.
> > 
> > To activate for selected file types (ex. html and css), place :let g:colorizer_auto_filetype='css,html' into your vimrc.

PR appreciated.

Best,
Christian
